#!/usr/bin/env python3
"""Cut the seal cipher's letters out of the script face as outlines.

The seal used to set its initials as SVG <text> in a script font, sized by a
guessed multiple of the die's radius. That guess cannot hold: a script capital
carries swashes that reach far outside its advance width, so the same font size
that fits a narrow letter runs a wide one off the wax. Fitting needs the real
outline bounds, and the browser will not give them before paint.

So the outlines are taken here, once, and checked into the source tree. The
component then knows exactly how wide each letter is and can scale the pair to
the struck face instead of hoping.

Usage:  python3 scripts/extract-cipher.py SB

Requires fonttools and brotli (pip install fonttools brotli). Run it again only
when the couple's initials change.
"""

import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / 'src/assets/fonts/great-vibes-400-latin.woff2'
OUT = ROOT / 'src/components/art/cipherGlyphs.ts'

HEADER = """/* Generated by scripts/extract-cipher.py. Do not edit by hand.

   The seal's initials as outlines cut from Great Vibes, the same script the
   page sets the couple's names in. Outlines rather than <text> because the
   seal has to fit its letters to the struck face, and only the real contour
   bounds say how wide a swashed capital actually is.

   Coordinates are the font's own em units with y running up, as the font
   stores them; `WaxSeal` flips and scales them. `bounds` is the tight contour
   box, which is what a swash makes different from the advance width.
*/

export interface CipherGlyph {
  /** Outline path in font units, y up. */
  readonly d: string
  /** Tight contour bounds: x0, y0, x1, y1. */
  readonly bounds: readonly [number, number, number, number]
}

/** Em size the outlines are expressed in. */
export const CIPHER_UPM = %d

export const CIPHER_GLYPHS: Readonly<Record<string, CipherGlyph>> = {
"""


def main() -> None:
    letters = sys.argv[1] if len(sys.argv) > 1 else 'SB'
    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    upm = font['head'].unitsPerEm

    rows = []
    for ch in sorted(set(letters)):
        name = cmap.get(ord(ch))
        if name is None:
            raise SystemExit(f'{FONT.name} has no glyph for {ch!r}')
        pen = SVGPathPen(glyphs, ntos=lambda v: str(round(v, 1)))
        glyphs[name].draw(pen)
        bounds = BoundsPen(glyphs)
        glyphs[name].draw(bounds)
        x0, y0, x1, y1 = (round(v, 1) for v in bounds.bounds)
        rows.append(
            f"  {ch}: {{\n    d: '{pen.getCommands()}',\n"
            f'    bounds: [{x0}, {y0}, {x1}, {y1}],\n  }},\n'
        )

    OUT.write_text(HEADER % upm + ''.join(rows) + '}\n')
    print(f'wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes) for {letters}')


if __name__ == '__main__':
    main()
